version: '3.8'

services:
  smart-intelligence-api:
    build: .
    container_name: smart-intelligence-api
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount .env file if it exists
      - ./.env:/app/backend/.env:ro
      # Optional: Mount data directories for persistence
      - ./backend/aidata:/app/backend/aidata:ro
      - ./frontend/media_files:/app/frontend/media_files:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: smart-intelligence-network