# Docker Compose configuration WITHOUT git
# Run your Docker Hub image with environment variables

services:
  smart-intelligence-api:
    # Use your Docker Hub image
    image: TU_USERNAME/hackmty_smart_intelligence:latest
    
    container_name: smart-intelligence-api
    ports:
      - "8001:8001"
    
    # Pass environment variables directly (no .env file needed)
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      
      # API Keys (replace with your actual keys)
      - GEMINI_API_KEY=AIzaSyDYrBDDTEXVzbb2xAlr2NxZDY4Fqoh4ORw
      - ELEVENLABS_API_KEY=sk_9d1375e7e03e0c325429bf29ac55ee9e8b7d1c932a13cd77
      
      # Snowflake credentials
      - SNOWFLAKE_ACCOUNT=HQVIWDY-CG89891
      - SNOWFLAKE_USER=DIEGOGM
      - SNOWFLAKE_PASSWORD=Diegogallo12001
      - SNOWFLAKE_WAREHOUSE=SNOWFLAKE_LEARNING_WH
      - SNOWFLAKE_DATABASE=SNOWFLAKE_LEARNING_DB
      - SNOWFLAKE_SCHEMA=PUBLIC
    
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: smart-intelligence-network

